server:
    port: 9191

spring:
    application:
        name: authorisation-service

    cloud:
        consul:
            host: http://consul.staging.etranzactng.net

    sleuth:
        enabled: true

    zipkin:
        baseUrl: http://172.17.10.83:9411
        sender:
            type: web

    datasource:
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/authorisation_service?useLegacyDatetimeCode=false&serverTimezone=Africa/Lagos
        driverClassName: com.mysql.cj.jdbc.Driver
    jackson:
        default-property-inclusion: NON_NULL
        mapper:
            accept-case-insensitive-properties: true

    flyway:
        user: root
        password: root
        locations: classpath:db/migration
        baseline-on-migrate: true
        check-location: true

    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true

    main:
        allow-bean-definition-overriding: true

management:
    server:
        port: 9190
    health:
        db.enabled: true
        show-details: ALWAYS
    endpoints:
        web.exposure.include: "*"

    metrics:
        export:
            prometheus:
                enabled: true

logging:
    file:
        name: logs/application.log
        max-history: 20
        max-size: 20MB
    level:
        org.apache.http: INFO
        org.springframework.cloud.sleuth: INFO
        org.springframework.web: INFO
        com.netflix.discovery.DiscoveryClient: INFO
        org.springframework.security: INFO
        org.hibernate: ERROR
        org.apache.kafka: WARN

hystrix:
    command:
        default:
            execution.isolation.thread.timeoutInMilliseconds: 5000
            circuitBreaker.errorThresholdPercentage: 60
            circuitBreaker.sleepWindowInMilliseconds: 20000
            circuitBreaker.requestVolumeThreshold: 10


