server:
    port: 9191
    servlet:
        context-path: /api

security:
    secret-key: AuthETransactNgView2021

spring:
    application:
        name: authorisation-service

    cloud:
        consul:
            host: http://consul.staging.etranzactng.net

    sleuth:
        enabled: true

    zipkin:
        baseUrl: http://172.17.10.83:9411
        sender:
            type: web

    datasource:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/authorisation_service?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=Africa/Lagos
      driverClassName: com.mysql.cj.jdbc.Driver
      initialization-mode: always

    jackson:
        default-property-inclusion: NON_NULL
        mapper:
            accept-case-insensitive-properties: true

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL55Dialect
        show-sql: false

    main:
        allow-bean-definition-overriding: true


management:
    server:
        port: 9190
    health:
        db.enabled: true
        show-details: ALWAYS
    endpoints:
        web.exposure.include: "*"

    metrics:
        export:
            prometheus:
                enabled: true

logging:
    file:
        name: logs/application.log
        max-history: 20
        max-size: 20MB
    level:
        org.apache.http: INFO
        org.springframework.cloud.sleuth: INFO
        org.springframework.web: INFO
        com.netflix.discovery.DiscoveryClient: INFO
        org.springframework.security: INFO
        org.hibernate: ERROR
        org.apache.kafka: WARN


hystrix:
    command:
        default:
            execution.isolation.thread.timeoutInMilliseconds: 5000
            circuitBreaker.errorThresholdPercentage: 60
            circuitBreaker.sleepWindowInMilliseconds: 20000
            circuitBreaker.requestVolumeThreshold: 10

#==================================================
  #  Mail Configuration                      #
  #==================================================
mail:
  #host: smtp.office365.com
  smtp: smtp.gmail.com
  username: ikejianwaleo@gmail.com
  password: $Ike08067950474
  sender: ETZ-EAGLE-EYE-MANAGER
  port: 587
  properties:
    debug: true
    mail:
      defaultEncoding: UTF-8
      smtp:
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
        auth: true
        starttls:
          enable: true
  protocol: smtp
